/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as PoolContractJson } from "../pool/Pool.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { DIAOracleValue, OracleData, PairInfo, AllStructs } from "./types";
import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace PoolTypes {
  export type Fields = {
    poolToken: HexString;
    poolDecimals: bigint;
    poolPair: HexString;
    collateralToken: HexString;
    collateralDecimals: bigint;
    collateralPair: HexString;
    exchangeRate: bigint;
    sPoolSupply: bigint;
    totalDeposits: bigint;
    totalBorrowed: bigint;
    collateralFactor: bigint;
    interestRate: bigint;
    oracle: HexString;
  };

  export type State = ContractState<Fields>;

  export type DepositedEvent = ContractEvent<{ who: Address; amount: bigint }>;
  export type WithdrawnEvent = ContractEvent<{ who: Address; amount: bigint }>;
  export type BorrowedEvent = ContractEvent<{
    who: Address;
    amount: bigint;
    collateralAmount: bigint;
  }>;
  export type RepaidEvent = ContractEvent<{ who: Address; amount: bigint }>;
  export type LiquidatedEvent = ContractEvent<{
    who: Address;
    liquidator: Address;
  }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    determineCollateralRatio: {
      params: CallContractParams<{
        tokenAmount: bigint;
        collateralAmount: bigint;
        threshhold: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
    deposit: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{ sPoolAmount: bigint }>;
      result: CallContractResult<null>;
    };
    depositCollateral: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    borrow: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    repay: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    liquidate: {
      params: CallContractParams<{ borrower: Address }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    determineCollateralRatio: {
      params: SignExecuteContractMethodParams<{
        tokenAmount: bigint;
        collateralAmount: bigint;
        threshhold: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    deposit: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ sPoolAmount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    depositCollateral: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    borrow: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    repay: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    liquidate: {
      params: SignExecuteContractMethodParams<{ borrower: Address }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = {
    loans?: Map<Address, bigint>;
    deposits?: Map<Address, bigint>;
    collateral?: Map<Address, bigint>;
  };
}

class Factory extends ContractFactory<PoolInstance, PoolTypes.Fields> {
  encodeFields(fields: PoolTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = {
    Deposited: 0,
    Withdrawn: 1,
    Borrowed: 2,
    Repaid: 3,
    Liquidated: 4,
  };
  consts = {
    PoolCodes: {
      CannotDepositZero: BigInt("0"),
      CannotBorrowZero: BigInt("1"),
      InsuffcientLiquidity: BigInt("2"),
      InsuffcientCollateral: BigInt("3"),
      NoActiveLoan: BigInt("4"),
    },
  };

  at(address: string): PoolInstance {
    return new PoolInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParams<PoolTypes.Fields, never, PoolTypes.Maps>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString, PoolTypes.Maps>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParams<PoolTypes.Fields, never, PoolTypes.Maps>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString, PoolTypes.Maps>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParams<PoolTypes.Fields, never, PoolTypes.Maps>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint, PoolTypes.Maps>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParams<PoolTypes.Fields, never, PoolTypes.Maps>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint, PoolTypes.Maps>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    determineCollateralRatio: async (
      params: TestContractParams<
        PoolTypes.Fields,
        { tokenAmount: bigint; collateralAmount: bigint; threshhold: bigint },
        PoolTypes.Maps
      >
    ): Promise<TestContractResult<bigint, PoolTypes.Maps>> => {
      return testMethod(
        this,
        "determineCollateralRatio",
        params,
        getContractByCodeHash
      );
    },
    deposit: async (
      params: TestContractParams<
        PoolTypes.Fields,
        { amount: bigint },
        PoolTypes.Maps
      >
    ): Promise<TestContractResult<null, PoolTypes.Maps>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParams<
        PoolTypes.Fields,
        { sPoolAmount: bigint },
        PoolTypes.Maps
      >
    ): Promise<TestContractResult<null, PoolTypes.Maps>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    depositCollateral: async (
      params: TestContractParams<
        PoolTypes.Fields,
        { amount: bigint },
        PoolTypes.Maps
      >
    ): Promise<TestContractResult<null, PoolTypes.Maps>> => {
      return testMethod(
        this,
        "depositCollateral",
        params,
        getContractByCodeHash
      );
    },
    borrow: async (
      params: TestContractParams<
        PoolTypes.Fields,
        { amount: bigint },
        PoolTypes.Maps
      >
    ): Promise<TestContractResult<null, PoolTypes.Maps>> => {
      return testMethod(this, "borrow", params, getContractByCodeHash);
    },
    repay: async (
      params: TestContractParams<
        PoolTypes.Fields,
        { amount: bigint },
        PoolTypes.Maps
      >
    ): Promise<TestContractResult<null, PoolTypes.Maps>> => {
      return testMethod(this, "repay", params, getContractByCodeHash);
    },
    liquidate: async (
      params: TestContractParams<
        PoolTypes.Fields,
        { borrower: Address },
        PoolTypes.Maps
      >
    ): Promise<TestContractResult<null, PoolTypes.Maps>> => {
      return testMethod(this, "liquidate", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: PoolTypes.Fields,
    asset?: Asset,
    address?: string,
    maps?: PoolTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const Pool = new Factory(
  Contract.fromJson(
    PoolContractJson,
    "=28-1=1+8=2-1=1+f=2-2+6=1-3+444f=723-1+5=181-1+c=40+7a7e0214696e73657274206174206d617020706174683a2000=25-1+3=287-1+e=40+7a7e0214696e73657274206174206d617020706174683a2000=349-1+6=278+7a7e021472656d6f7665206174206d617020706174683a2000=46+7a7e021472656d6f7665206174206d617020706174683a2000=32",
    "4225173d8b3089b8801b31fab5fed2e0ac7352db99a6a8efefecfad94121931c",
    AllStructs
  )
);
registerContract(Pool);

// Use this class to interact with the blockchain
export class PoolInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    loans: new RalphMap<Address, bigint>(
      Pool.contract,
      this.contractId,
      "loans"
    ),
    deposits: new RalphMap<Address, bigint>(
      Pool.contract,
      this.contractId,
      "deposits"
    ),
    collateral: new RalphMap<Address, bigint>(
      Pool.contract,
      this.contractId,
      "collateral"
    ),
  };

  async fetchState(): Promise<PoolTypes.State> {
    return fetchContractState(Pool, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeDepositedEvent(
    options: EventSubscribeOptions<PoolTypes.DepositedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Pool.contract,
      this,
      options,
      "Deposited",
      fromCount
    );
  }

  subscribeWithdrawnEvent(
    options: EventSubscribeOptions<PoolTypes.WithdrawnEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Pool.contract,
      this,
      options,
      "Withdrawn",
      fromCount
    );
  }

  subscribeBorrowedEvent(
    options: EventSubscribeOptions<PoolTypes.BorrowedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Pool.contract,
      this,
      options,
      "Borrowed",
      fromCount
    );
  }

  subscribeRepaidEvent(
    options: EventSubscribeOptions<PoolTypes.RepaidEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Pool.contract,
      this,
      options,
      "Repaid",
      fromCount
    );
  }

  subscribeLiquidatedEvent(
    options: EventSubscribeOptions<PoolTypes.LiquidatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Pool.contract,
      this,
      options,
      "Liquidated",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | PoolTypes.DepositedEvent
      | PoolTypes.WithdrawnEvent
      | PoolTypes.BorrowedEvent
      | PoolTypes.RepaidEvent
      | PoolTypes.LiquidatedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(Pool.contract, this, options, fromCount);
  }

  view = {
    getSymbol: async (
      params?: PoolTypes.CallMethodParams<"getSymbol">
    ): Promise<PoolTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        Pool,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: PoolTypes.CallMethodParams<"getName">
    ): Promise<PoolTypes.CallMethodResult<"getName">> => {
      return callMethod(
        Pool,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: PoolTypes.CallMethodParams<"getDecimals">
    ): Promise<PoolTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        Pool,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: PoolTypes.CallMethodParams<"getTotalSupply">
    ): Promise<PoolTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        Pool,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    determineCollateralRatio: async (
      params: PoolTypes.CallMethodParams<"determineCollateralRatio">
    ): Promise<PoolTypes.CallMethodResult<"determineCollateralRatio">> => {
      return callMethod(
        Pool,
        this,
        "determineCollateralRatio",
        params,
        getContractByCodeHash
      );
    },
    deposit: async (
      params: PoolTypes.CallMethodParams<"deposit">
    ): Promise<PoolTypes.CallMethodResult<"deposit">> => {
      return callMethod(Pool, this, "deposit", params, getContractByCodeHash);
    },
    withdraw: async (
      params: PoolTypes.CallMethodParams<"withdraw">
    ): Promise<PoolTypes.CallMethodResult<"withdraw">> => {
      return callMethod(Pool, this, "withdraw", params, getContractByCodeHash);
    },
    depositCollateral: async (
      params: PoolTypes.CallMethodParams<"depositCollateral">
    ): Promise<PoolTypes.CallMethodResult<"depositCollateral">> => {
      return callMethod(
        Pool,
        this,
        "depositCollateral",
        params,
        getContractByCodeHash
      );
    },
    borrow: async (
      params: PoolTypes.CallMethodParams<"borrow">
    ): Promise<PoolTypes.CallMethodResult<"borrow">> => {
      return callMethod(Pool, this, "borrow", params, getContractByCodeHash);
    },
    repay: async (
      params: PoolTypes.CallMethodParams<"repay">
    ): Promise<PoolTypes.CallMethodResult<"repay">> => {
      return callMethod(Pool, this, "repay", params, getContractByCodeHash);
    },
    liquidate: async (
      params: PoolTypes.CallMethodParams<"liquidate">
    ): Promise<PoolTypes.CallMethodResult<"liquidate">> => {
      return callMethod(Pool, this, "liquidate", params, getContractByCodeHash);
    },
  };

  transact = {
    getSymbol: async (
      params: PoolTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<PoolTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(Pool, this, "getSymbol", params);
    },
    getName: async (
      params: PoolTypes.SignExecuteMethodParams<"getName">
    ): Promise<PoolTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(Pool, this, "getName", params);
    },
    getDecimals: async (
      params: PoolTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<PoolTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(Pool, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: PoolTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<PoolTypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(Pool, this, "getTotalSupply", params);
    },
    determineCollateralRatio: async (
      params: PoolTypes.SignExecuteMethodParams<"determineCollateralRatio">
    ): Promise<
      PoolTypes.SignExecuteMethodResult<"determineCollateralRatio">
    > => {
      return signExecuteMethod(Pool, this, "determineCollateralRatio", params);
    },
    deposit: async (
      params: PoolTypes.SignExecuteMethodParams<"deposit">
    ): Promise<PoolTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(Pool, this, "deposit", params);
    },
    withdraw: async (
      params: PoolTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<PoolTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(Pool, this, "withdraw", params);
    },
    depositCollateral: async (
      params: PoolTypes.SignExecuteMethodParams<"depositCollateral">
    ): Promise<PoolTypes.SignExecuteMethodResult<"depositCollateral">> => {
      return signExecuteMethod(Pool, this, "depositCollateral", params);
    },
    borrow: async (
      params: PoolTypes.SignExecuteMethodParams<"borrow">
    ): Promise<PoolTypes.SignExecuteMethodResult<"borrow">> => {
      return signExecuteMethod(Pool, this, "borrow", params);
    },
    repay: async (
      params: PoolTypes.SignExecuteMethodParams<"repay">
    ): Promise<PoolTypes.SignExecuteMethodResult<"repay">> => {
      return signExecuteMethod(Pool, this, "repay", params);
    },
    liquidate: async (
      params: PoolTypes.SignExecuteMethodParams<"liquidate">
    ): Promise<PoolTypes.SignExecuteMethodResult<"liquidate">> => {
      return signExecuteMethod(Pool, this, "liquidate", params);
    },
  };

  async multicall<Calls extends PoolTypes.MultiCallParams>(
    calls: Calls
  ): Promise<PoolTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends PoolTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<PoolTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends PoolTypes.MultiCallParams | PoolTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Pool, this, callss, getContractByCodeHash);
  }
}
